### ISSUE TITLE
My computer broken

### ISSUE THREAD

**Issue by 0liverScott** [incheon-kim/tarkov-settings#11]
my computer crashed when i'm going into my hideout and only saturation filter doesn't turn off on my computer. i can't find solution plz help me... saturation filter just applied on my computer.

**Comment by 0liverScott** [comment]
형님 채도만 올라가서 안빼져요 컴터에 영구적용 됐어요 살려주세요

**Comment by incheon-kim** [comment]
프로그램을 일단 끄신 다음 Nvidia 제어판에서 디지털 바이브런스 값을 조절하시면 됩니다 :)

**Comment by 0liverScott** [comment]
감사합니다 고쳐졌습니다 좋은 프로그램 늘 잘 쓰고있습니다
