### ISSUE TITLE
Any plans for other games?

### ISSUE THREAD

**Issue by mohcow** [incheon-kim/tarkov-settings#13]
I'd like to use this for Counter-strike. maybe a way to enter a custom .exe instead of just tarkov?

**Comment by incheon-kim** [comment]
When you open settings.json file you can see "EscapeFromTarkov" at some kind of list with wrapped with bracket.
Try to add Counter-Strike's process name without ".exe"

**Comment by mohcow** [comment]
Thank you that works for now. I read in another issue that you rewriting the whole app, is this still in the cards?

**Comment by incheon-kim** [comment]
I am still rewriting but i don't have much free time as i had years ago. but it will be there.
