### ISSUE TITLE
Nvidia GPU not found!

### ISSUE THREAD

**Issue by shensmobile** [incheon-kim/tarkov-settings#15]
![image](https://github.com/incheon-kim/tarkov-settings/assets/25826352/4d015efa-712a-4894-b359-37685550906b)

Recently booted Tarkov back up and tarkov-settings is giving me this error.  Is it due to a driver compatibility issue? 

PC Specs: 5800x3d + 3080

**Comment by incheon-kim** [comment]
Please type in these command in cmd or powershell and share the results.
`wmic path win32_VideoController get name`
`wmic path win32_VideoController get description`

**Comment by shensmobile** [comment]
wmic path win32_VideoController get name:
Virtual Desktop Monitor
NVIDIA GeForce RTX 3080

wmic path win32_VideoController get description
Virtual Desktop Monitor
NVIDIA GeForce RTX 3080

Ah it might be due to my virtual monitor?

**Comment by incheon-kim** [comment]
I think it is. It can be easily fixed. give me some minutes.

**Comment by shensmobile** [comment]
You're my hero!

**Comment by incheon-kim** [comment]
1.2.1 released
now it is single executable. roughly tested so i need someone to test it.

**Comment by shensmobile** [comment]
It appears to be working!  I'll close the issue for now and re-open if I find bugs.
