### ISSUE TITLE
Digital Vibrance (Saturation) only goes up to 69?

### ISSUE THREAD

**Issue by jonhermansen** [incheon-kim/tarkov-settings#24]
Hi, I am trying your project, coming from vibranceGUI which lately has not been working well on EFT.

This is not so much an issue, just a question. If I set Digital Vibrance to 69, is it effectively the same as setting it at 100% in the NVIDIA Control Panel?

Thank you for your help and excellent open source project!

**Comment by incheon-kim** [comment]
Yes it is. 69 is maximum value of digital vibrance according to NVAPI (Nvidia API).
I can change it to ratio but i just used raw value because of my laziness :)

**Comment by jonhermansen** [comment]
@incheon-kim Thank you for the quick response. It's no problem, just part of my learning curve getting used to it.
