### ISSUE TITLE
Is there a settings.json?

### ISSUE THREAD

**Issue by scheMeZa** [incheon-kim/tarkov-settings#9]
I've read that there should be one, but I can't find setting.json?

**Comment by incheon-kim** [comment]
`setting.json` file will be written when you close the application.

**Comment by scheMeZa** [comment]
Oh. I've been running it for a few days, even "X"ing out of it. I clicked "Exit" in the taskbar and it created my settings.json file. Thanks.

**Comment by scheMeZa** [comment]
Coming from Vibrance GUI, I like your app way more. 
It just lacks support for easily selecting other apps. 
Gamma is something vibrance GUI has been struggling to implement for years now.

**Comment by incheon-kim** [comment]
FYI, I am rewriting this app with .NET 6 + WPF with additional features like hotkeys, easier app selecting and etc.

**Comment by scheMeZa** [comment]
Add me on Discord - would love to discuss: scheMe#1514

**Comment by panicaz** [comment]
> FYI, I am rewriting this app with .NET 6 + WPF with additional features like hotkeys, easier app selecting and etc. Of course, I know saving settings by killing app feels ridiculous. It will be fixed too.

Hey love your app. 
Can you add manual on/off buttons without checking if process is in focus for fullscreen users? It feels so much smoother for me in fullscreen mode so I can't use borderless.
Spend 4 hours trying myself but my C# skills is not good enough for it.

**Comment by incheon-kim** [comment]
> Can you add manual on/off buttons without checking if process is in focus for fullscreen users? It feels so much smoother for me in fullscreen mode so I can't use borderless.
Spend 4 hours trying myself but my C# skills is not good enough for it.

This app doesn't detect if the app is in fullscreen mode or not. It just doesn't work if game is in fullscreen because of limitation of Windows API. Anyway, Manual enable/disable toggle will be there.
